"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend, AreaChart, Area
} from "recharts";

// TypeScript definitions to match your AnalyticsDao JSON format exactly
interface AnalyticsData {
  totalCustomers: number;
  totalRevenue: number;
  pendingRevenue: number;
  invoiceCounts: Record<string, number>;
  rateplanPopularity: Record<string, number>;
  usageDistribution: Record<string, number>;
}

export default function AdminDashboard() {
  const router = useRouter();
  const [data, setData] = useState<AnalyticsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    async function fetchDashboardData() {
      try {
        const res = await fetch("/api/analytics");
        
        if (res.status === 401 || res.status === 403) {
          router.push("/login");
          return;
        }

        if (!res.ok) throw new Error("Failed to load dashboard metrics");

        const json = await res.json();
        setData(json);
      } catch (err: any) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    }

    fetchDashboardData();
  }, [router]);

  if (loading) {
    return (
      <div className="min-h-screen bg-surface-950 flex flex-col items-center justify-center gap-4">
        <div className="w-8 h-8 border-2 border-accent-blue border-t-transparent rounded-full animate-spin" />
        <p className="text-sm text-slate-400 font-mono">Querying operational metrics...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-surface-950 flex flex-col items-center justify-center gap-4 text-center px-4">
        <div className="p-4 bg-rose-500/10 border border-rose-500/20 rounded-2xl max-w-md">
          <p className="text-rose-400 font-medium mb-2">Data Stream Disrupted</p>
          <p className="text-xs text-slate-400">{error}</p>
        </div>
        <button onClick={() => window.location.reload()} className="px-4 py-2 bg-surface-800 text-sm font-medium rounded-xl border border-surface-700 hover:bg-surface-700 transition-all">
          Retry Connection
        </button>
      </div>
    );
  }

  // Transform Java maps into array structures that Recharts can draw
  const rateplanChartData = data ? Object.entries(data.rateplanPopularity).map(([name, count]) => ({ name, count })) : [];
  const usageChartData = data ? Object.entries(data.usageDistribution).map(([name, units]) => ({ name, units })) : [];
  const invoiceChartData = data ? Object.entries(data.invoiceCounts).map(([status, count]) => ({ status, count })) : [];

  const COLORS = ["#3b82f6", "#10b981", "#8b5cf6", "#f59e0b", "#f43f5e"];

  return (
    <div className="min-h-screen bg-surface-950 text-slate-100 p-6 md:p-8">
      {/* Top Banner Row */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-8 border-b border-surface-800 pb-6">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Executive Billing Command</h1>
          <p className="text-sm text-slate-400">Real-time analytical trends generated by Java Mediation Core</p>
        </div>
        <button 
          onClick={async () => {
            await fetch("/api/auth", { method: "DELETE" });
            router.push("/login");
          }}
          className="self-start md:self-auto px-4 py-2 text-xs font-medium bg-surface-900 border border-surface-700 rounded-xl text-slate-300 hover:text-white hover:bg-surface-800 transition-all"
        >
          Disconnect Session
        </button>
      </div>

      {/* KPI Metric Grid Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
        <div className="glass-card p-6">
          <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-1">Active Subscribers</p>
          <p className="text-3xl font-bold font-mono text-white">{data?.totalCustomers.toLocaleString()}</p>
        </div>
        <div className="glass-card p-6 border-l-4 border-l-accent-emerald">
          <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-1">Settled Revenue</p>
          <p className="text-3xl font-bold font-mono text-accent-emerald">${data?.totalRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
        </div>
        <div className="glass-card p-6 border-l-4 border-l-accent-amber">
          <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-1">Outstanding Claims</p>
          <p className="text-3xl font-bold font-mono text-accent-amber">${data?.pendingRevenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</p>
        </div>
      </div>

      {/* Graphical Chart Cluster Analytics Row */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Chart 1: Rateplan Subscription Volumes */}
        <div className="glass-card p-6">
          <h3 className="text-sm font-semibold text-slate-200 mb-6">Package Distribution Density</h3>
          <div className="h-80 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={rateplanChartData}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1f1f2b" vertical={false} />
                <XAxis dataKey="name" stroke="#94a3b8" fontSize={12} tickLine={false} />
                <YAxis stroke="#94a3b8" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip contentStyle={{ backgroundColor: "#111115", borderColor: "#2a2a3a", borderRadius: "12px" }} />
                <Bar dataKey="count" fill="#3b82f6" radius={[4, 4, 0, 0]} maxBarSize={45} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Chart 2: Network Traffic Resource Usage */}
        <div className="glass-card p-6">
          <h3 className="text-sm font-semibold text-slate-200 mb-6">Aggregated Rating Usage Type</h3>
          <div className="h-80 w-full flex items-center justify-center">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={usageChartData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={90}
                  paddingAngle={5}
                  dataKey="units"
                  nameKey="name"
                >
                  {usageChartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                  ))}
                </Pie>
                <Tooltip contentStyle={{ backgroundColor: "#111115", borderColor: "#2a2a3a", borderRadius: "12px" }} />
                <Legend verticalAlign="bottom" height={36} iconType="circle" wrapperStyle={{ fontSize: "12px" }} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
}